version: '2.1'
services:
  blog:
    container_name: blog
    build: .
    ports:
      - '8080:8080'
    environment:
      PORT: 8080
      NODE_ENV: development
      CONTENT_ENDPOINT: http://content-service:3000
    volumes:
      - ./src:/usr/src/app/src
    entrypoint: npm run dev
  content-service:
    container_name: content-service
    build: ../content-service
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      NODE_ENV: development
      RESULTS_PAGE_SIZE: 10
      API_ENDPOINT: https://hadrian-blog.prismic.io/api
    volumes:
      - ../content-service:/usr/src/app
    entrypoint: npm run dev
  varnish:
    container_name: varnish
    depends_on:
      - content-service
      - blog
    build: ../varnish
    ports:
      - '80:80'
    networks:
      default:
        aliases:
          - content-cache
